// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
const renderLicenseLink =require('./asset/generateMarkdown');
const responseLink = require('./asset/generateMarkdown');
var licenseLink = [];
let licenseSection = ' ';





inquirer
  .prompt([
    {
        name: "fullName",
        message: "Enter full name"
    }, 
    {
        name: "date",
        message: "enter the date"
    }, 
    {
        name: "projectTitle",
        message: "what is your project titled"
    }, 
    {
        name: "description",
        message: "write a good description of your project"
    }, 
    {
        name: "installations",
        message:"how do we install your app"
    }, 
    {
        name: "usage",
        message: "write usage information here",
    }, 
    {
        type: 'checkbox',
        message: 'choose your license',
        name: "license",
        choices:[`MIT`,`Boost Software`,`apache`],
    }, 
        
    {
        type: 'checkbox',
        name: 'badgeColor',
        message: 'pick a color',
        choices:['red','yellowgreen','orange','blue'],
   }, 
]).then((responce) => {
    const readMePage= generateReadMe(responce);
    if(responce.license == 'MIT') {
    
         licenseSection =`MIT License
  
        Copyright (c) ${responce.date} ${responce.fullName}
        
        Permission is hereby granted, free of charge, to any person obtaining a copy
        of this software and associated documentation files (the "Software"), to deal
        in the Software without restriction, including without limitation the rights
        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        copies of the Software, and to permit persons to whom the Software is
        furnished to do so, subject to the following conditions:
        
        The above copyright notice and this permission notice shall be included in all
        copies or substantial portions of the Software.
        
        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
        SOFTWARE.`;
   }
   else if(responce.license == 'Boost Software') {

        licenseSection = `Boost Software License - Version 1.0 - August 17th, 2003
  
        Permission is hereby granted, free of charge, to any person or organization
        obtaining a copy of the software and accompanying documentation covered by
        this license (the "Software") to use, reproduce, display, distribute,
        execute, and transmit the Software, and to prepare derivative works of the
        Software, and to permit third-parties to whom the Software is furnished to
        do so, all subject to the following:
        
        The copyright notices in the Software and this entire statement, including
        the above license grant, this restriction and the following disclaimer,
        must be included in all copies of the Software, in whole or in part, and
        all derivative works of the Software, unless such copies or derivative
        works are solely in the form of machine-executable object code generated by
        a source language processor.
        
        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
        SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
        FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
        ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
        DEALINGS IN THE SOFTWARE.`;
   } else{
         licenseSection= null;
         
   }

    fs.writeFile('README.md', readMePage, (err) =>
    err ? console.log(err) : console.log('sucess')
    );
})


const generateReadMe= (responce,licenseSection) => {
    return`


# ${responce.projectTitle}

## Description

 ${responce.description}


## Table of Contents (Optional)

If your README is very long, add a table of contents to make it easy for users to find what they need.

* [Installation](#installation)
* [Usage](#usage)
* [Credits](#credits)
* [License](#license)


## Installation

${responce.installations}


## Usage 

${responce.usage}



## Credits

List your collaborators, if any, with links to their GitHub profiles.

If you used any third-party assets that require attribution, list the creators with links to their primary web presence in this section.

If you followed tutorials, include links to those here as well.


## License

${responce.license}

'https://choosealicense.com/licenses/${responce.license}/

${licenseSection}



---

🏆 The sections listed above are the minimum for a good README, but your project will ultimately determine the content of this document. You might also want to consider adding the following sections.

## Badges


https://img.shields.io/badge/license-${responce.license}-${responce.badgeColor}

## Features

If your project has a lot of features, consider adding a heading called "Features" and listing them there.

## Contributing

If you created an application or package and would like other developers to contribute it, you will want to add guidelines for how to do so. The [Contributor Covenant](https://www.contributor-covenant.org/) is an industry standard, but you can always write your own.

## Tests

Go the extra mile and write tests for your application. Then provide examples on how to run them.

---

© 2023 edX Boot Camps LLC. Confidential and Proprietary. All Rights Reserved.
`
}
// // TODO: Create an array of questions for user input
// newLicenseSection =JSON
// const questions = [];

// // TODO: Create a function to write README file
// function writeToFile(fileName, data) {}

// // TODO: Create a function to initialize app
// function init() {}

// // Function call to initialize app
// init();
